services:
  plantuml-server:
    build:
      context: .
      dockerfile: Dockerfile.jetty
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    ports:
      - 9999:8080
    environment:
      - BASE_URL=
